### ISSUE TITLE
Header mismatch

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#1]
Your header:
![image](https://cloud.githubusercontent.com/assets/25591824/23180599/9be247fc-f87a-11e6-9429-7d1c673dbb57.png)

Must be like this:
![image](https://cloud.githubusercontent.com/assets/25591824/23180613/a6e95d2a-f87a-11e6-9399-09206424eed7.png)

**Comment by Oksana-Shuliak** [comment]
Got it
![image](https://cloud.githubusercontent.com/assets/25491466/23437511/228d5cfa-fe17-11e6-88d6-c6b31984ca28.png)

**Comment by eko24ive** [comment]
Really smooth !
