### ISSUE TITLE
Headers mismatch

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#3]
Following headers:
- portfolio
![image](https://cloud.githubusercontent.com/assets/25591824/23180706/f4b0cb74-f87a-11e6-91d4-af83376b8108.png)
- about
![image](https://cloud.githubusercontent.com/assets/25591824/23180742/2213fbfe-f87b-11e6-827c-613e45598e57.png)
- contact me
![image](https://cloud.githubusercontent.com/assets/25591824/23180755/298d5c72-f87b-11e6-831f-69fafa809d11.png)

Should have bigger font size and also bigger star size and its lines, like this:
![image](https://cloud.githubusercontent.com/assets/25591824/23180716/0443fade-f87b-11e6-9763-a38e79c551e3.png)

**Comment by Oksana-Shuliak** [comment]
Finally done
But, maybe not so bold
![image](https://cloud.githubusercontent.com/assets/25491466/23437404/b3df9084-fe16-11e6-852c-c7a0ba244d49.png)
![image](https://cloud.githubusercontent.com/assets/25491466/23437417/bc19e330-fe16-11e6-966a-1ef6e0272d2a.png)
![image](https://cloud.githubusercontent.com/assets/25491466/23437426/c52991aa-fe16-11e6-81c3-a87693f0268e.png)

**Comment by eko24ive** [comment]
I think its fits into design 😉
