### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#4]
This section:
![image](https://cloud.githubusercontent.com/assets/25591824/23180811/559369ba-f87b-11e6-95dd-c48a19881715.png)

Must be fixed with padding issues and button styles mismatch:
![image](https://cloud.githubusercontent.com/assets/25591824/23180827/64f27360-f87b-11e6-8d1d-8ef6f66a5ce3.png)

**Comment by Oksana-Shuliak** [comment]
Changed
![image](https://cloud.githubusercontent.com/assets/25491466/23437332/67b5a52c-fe16-11e6-89a0-f3cf3d62955a.png)

**Comment by eko24ive** [comment]
It's nice to see it done right !
