### ISSUE TITLE
Contact section

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#5]
Contact section is way to big.
![image](https://cloud.githubusercontent.com/assets/25591824/23180850/7e01a1d2-f87b-11e6-83ed-5bd2970d9411.png)

Also decrease input padding and fix button styles:
![image](https://cloud.githubusercontent.com/assets/25591824/23180859/8d1b3688-f87b-11e6-9a39-70c73a21e689.png)

**Comment by Oksana-Shuliak** [comment]
Check. please my work. I've changed everything except of button. Have some problems. I don't know how to place it like in example.

**Comment by eko24ive** [comment]
Everything is fine, except you are using `type="text"` for **Message** field.
Try to recall what tag we should use for big text area input.

**Comment by Oksana-Shuliak** [comment]
Ok, I've changed to <textarea>

**Comment by Oksana-Shuliak** [comment]
What about this button? Can't align it correctly
![image](https://cloud.githubusercontent.com/assets/25491466/23437589/4f0903ba-fe17-11e6-8ecb-11c5bfd52c7a.png)

**Comment by eko24ive** [comment]
Have you tried to inspect parent elements of button and their css rules ?
HINT: Take a look at `.contact .row` in your css code

**Comment by Oksana-Shuliak** [comment]
I've solved the problem with button

**Comment by eko24ive** [comment]
Awesome !
