### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#6]
This section:
![image](https://cloud.githubusercontent.com/assets/25591824/23180932/c0c4da0c-f87b-11e6-9b53-d2574c5087a5.png)

Add more padding like on design:
![image](https://cloud.githubusercontent.com/assets/25591824/23180957/d2319154-f87b-11e6-8a21-80f2342ecb94.png)

Fix font awesome icons:
![image](https://cloud.githubusercontent.com/assets/25591824/23180974/dd0b3dfa-f87b-11e6-8bfb-704e80915a0c.png)

**Comment by Oksana-Shuliak** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/25491466/23437286/396e372e-fe16-11e6-8fd2-535e53abae1e.png)

**Comment by eko24ive** [comment]
Nicely done !
