### ISSUE TITLE
Overlay issue

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#7]
Width of your page is bigger than default device width:
![image](https://cloud.githubusercontent.com/assets/25591824/23181038/1404bc0a-f87c-11e6-990a-2eaf1cda3fa1.png)

Fix it the way we wouldn't take additional width and fit into horizontal screen size

**Comment by Oksana-Shuliak** [comment]
It's okay now
![image](https://cloud.githubusercontent.com/assets/25491466/23437258/15e84452-fe16-11e6-86fc-6773aa892ca8.png)

**Comment by eko24ive** [comment]
Good job !
